services:
  # Backend API service
  - type: web
    name: breast-cancer-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/keerthana777z/Breast-Cancer-Detection-Application.git
    branch: main
    buildFilter:
      paths:
        - BACKEND/**
    envVars:
      - key: PORT
        value: 5003
      - key: PYTHON_VERSION
        value: 3.10.0

  # Frontend web service
  - type: web
    name: breast-cancer-detection-frontend
    env: static
    buildCommand: cd my-app && npm install && npm run build
    staticPublishPath: my-app/build
    repo: https://github.com/keerthana777z/Breast-Cancer-Detection-Application.git
    branch: main
    buildFilter:
      paths:
        - my-app/**
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
