name: Complete CI/CD Pipeline

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install frontend dependencies
      run: |
        cd my-app
        npm ci

    - name: Install backend dependencies
      run: |
        cd BACKEND
        pip install -r requirements.txt

    - name: Run frontend tests
      run: |
        cd my-app
        CI=true npm test -- --watchAll=false --transformIgnorePatterns "node_modules/(?!axios)/"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        # Install Docker Compose v1 for compatibility
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Run Docker containers
      run: |
        docker-compose up -d
        sleep 10  # Give containers time to start

    - name: Check if containers are running
      run: |
        docker-compose ps

    - name: Check backend health
      run: |
        curl -f http://localhost:5003 || echo "Backend not responding"

    - name: Stop Docker containers
      run: |
        docker-compose down

  deploy:
    name: Deploy with Docker Compose
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Verify model file exists
      run: |
        cd BACKEND
        ls -la
        echo "Checking for model file..."
        if [ -f "my_model3.h5" ]; then
          echo "✅ Model file found: my_model3.h5"
        else
          echo "❌ Model file not found!"
          exit 1
        fi

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./BACKEND
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./my-app
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-frontend:latest

    - name: Deploy to server
      if: github.event_name != 'pull_request'
      run: |
        echo "Deploying to server..."

        # Create a docker-compose.yml file for deployment
        cat > docker-compose.prod.yml << EOF
        version: '3.8'

        services:
          backend:
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-backend:latest
            ports:
              - "5003:5003"
            environment:
              - MODEL_PATH=/app/my_model3.h5
              - PORT=5003
            restart: always

          frontend:
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-frontend:latest
            ports:
              - "8080:80"
            depends_on:
              - backend
            restart: always
        EOF

        # For demonstration, we'll just run it locally
        # In a real scenario, you would copy this file to your server and run it there
        docker-compose -f docker-compose.prod.yml up -d

        echo "Application deployed successfully!"
        echo "Frontend: http://localhost:8080"
        echo "Backend: http://localhost:5003"


