name: Deploy Frontend to GitHub Pages

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'my-app/**'  # Only run when changes are made to the frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: my-app/package-lock.json
        
    - name: Install dependencies
      run: |
        cd my-app
        npm ci
        
    - name: Build
      run: |
        cd my-app
        npm run build
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: my-app/build  # The folder the action should deploy
        branch: gh-pages  # The branch the action should deploy to
