name: Deploy with SSH Deploy Keys

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create simple demo page
        run: |
          mkdir -p demo
          cat > demo/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Breast Cancer Detection Application</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
                color: #333;
              }
              h1 {
                color: #e91e63;
                text-align: center;
              }
              .container {
                border: 1px solid #ddd;
                border-radius: 5px;
                padding: 20px;
                margin-top: 20px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.1);
              }
              .success {
                background-color: #e8f5e9;
                padding: 10px;
                border-radius: 5px;
                text-align: center;
                margin: 20px 0;
              }
              .features {
                margin-top: 30px;
              }
              .features h2 {
                color: #2196f3;
              }
              .features ul {
                list-style-type: square;
              }
            </style>
          </head>
          <body>
            <h1>Breast Cancer Detection Application</h1>

            <div class="success">
              <h2>✅ Deployment Successful!</h2>
              <p>The CI/CD pipeline with SSH deploy keys is working correctly.</p>
            </div>

            <div class="container">
              <h2>About This Application</h2>
              <p>This application uses machine learning to detect breast cancer from histopathological images.</p>

              <div class="features">
                <h2>Features</h2>
                <ul>
                  <li>Upload histopathological images for analysis</li>
                  <li>Real-time prediction using a trained deep learning model</li>
                  <li>Responsive web interface</li>
                  <li>Dockerized application for easy deployment</li>
                  <li>CI/CD pipeline with SSH deploy key authentication</li>
                </ul>
              </div>
            </div>
          </body>
          </html>
          EOF

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_DEPLOY_KEY }}
          known_hosts: unnecessary
          if_key_exists: fail

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
          publish_dir: ./demo
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages with SSH deploy key'
